name: meu_app
description: Um novo app Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  


flutter:
  uses-material-design: true
